export const COUNTRIES = [
    { code: 'AF', name: 'Afghanistan', supported: false },
    { code: 'AL', name: 'Albania', supported: false },
    { code: 'DZ', name: 'Algeria', supported: false },
    { code: 'AD', name: 'Andorra', supported: false },
    { code: 'AO', name: 'Angola', supported: false },
    { code: 'AR', name: 'Argentina', supported: true },
    { code: 'AU', name: 'Australia', supported: true },
    { code: 'AT', name: 'Austria', supported: true },
    { code: 'BE', name: 'Belgium', supported: true },
    { code: 'BR', name: 'Brazil', supported: true },
    { code: 'CA', name: 'Canada', supported: true },
    { code: 'CL', name: 'Chile', supported: true },
    { code: 'CN', name: 'China', supported: true },
    { code: 'CO', name: 'Colombia', supported: true },
    { code: 'CZ', name: 'Czech Republic', supported: true },
    { code: 'DK', name: 'Denmark', supported: true },
    { code: 'EG', name: 'Egypt', supported: true },
    { code: 'FI', name: 'Finland', supported: true },
    { code: 'FR', name: 'France', supported: true },
    { code: 'DE', name: 'Germany', supported: true },
    { code: 'GR', name: 'Greece', supported: true },
    { code: 'HK', name: 'Hong Kong', supported: true },
    { code: 'HU', name: 'Hungary', supported: true },
    { code: 'IN', name: 'India', supported: true },
    { code: 'ID', name: 'Indonesia', supported: true },
    { code: 'IE', name: 'Ireland', supported: true },
    { code: 'IL', name: 'Israel', supported: true },
    { code: 'IT', name: 'Italy', supported: true },
    { code: 'JP', name: 'Japan', supported: true },
    { code: 'MY', name: 'Malaysia', supported: true },
    { code: 'MX', name: 'Mexico', supported: true },
    { code: 'NL', name: 'Netherlands', supported: true },
    { code: 'NZ', name: 'New Zealand', supported: true },
    { code: 'NO', name: 'Norway', supported: true },
    { code: 'PE', name: 'Peru', supported: true },
    { code: 'PH', name: 'Philippines', supported: true },
    { code: 'PL', name: 'Poland', supported: true },
    { code: 'PT', name: 'Portugal', supported: true },
    { code: 'RU', name: 'Russia', supported: true },
    { code: 'SA', name: 'Saudi Arabia', supported: true },
    { code: 'SG', name: 'Singapore', supported: true },
    { code: 'ZA', name: 'South Africa', supported: true },
    { code: 'KR', name: 'South Korea', supported: true },
    { code: 'ES', name: 'Spain', supported: true },
    { code: 'SE', name: 'Sweden', supported: true },
    { code: 'CH', name: 'Switzerland', supported: true },
    { code: 'TW', name: 'Taiwan', supported: true },
    { code: 'TH', name: 'Thailand', supported: true },
    { code: 'TR', name: 'Turkey', supported: true },
    { code: 'AE', name: 'United Arab Emirates', supported: true },
    { code: 'GB', name: 'United Kingdom', supported: true },
    { code: 'US', name: 'United States', supported: true },
    { code: 'VN', name: 'Vietnam', supported: true },
];
