export interface Currency {
    code: string;
    name: string;
    country: string;
    countryCode: string;
}

export const CURRENCIES: Currency[] = [
    { code: 'USD', name: 'United States Dollar', country: 'United States', countryCode: 'US' },
    { code: 'EUR', name: 'Euro', country: 'European Union', countryCode: 'EU' },
    { code: 'GBP', name: 'British Pound Sterling', country: 'United Kingdom', countryCode: 'GB' },
    { code: 'JPY', name: 'Japanese Yen', country: 'Japan', countryCode: 'JP' },
    { code: 'AUD', name: 'Australian Dollar', country: 'Australia', countryCode: 'AU' },
    { code: 'CAD', name: 'Canadian Dollar', country: 'Canada', countryCode: 'CA' },
    { code: 'CHF', name: 'Swiss Franc', country: 'Switzerland', countryCode: 'CH' },
    { code: 'CNY', name: 'Chinese Yuan', country: 'China', countryCode: 'CN' },
    { code: 'HKD', name: 'Hong Kong Dollar', country: 'Hong Kong', countryCode: 'HK' },
    { code: 'NZD', name: 'New Zealand Dollar', country: 'New Zealand', countryCode: 'NZ' },
    { code: 'SEK', name: 'Swedish Krona', country: 'Sweden', countryCode: 'SE' },
    { code: 'KRW', name: 'South Korean Won', country: 'South Korea', countryCode: 'KR' },
    { code: 'SGD', name: 'Singapore Dollar', country: 'Singapore', countryCode: 'SG' },
    { code: 'NOK', name: 'Norwegian Krone', country: 'Norway', countryCode: 'NO' },
    { code: 'MXN', name: 'Mexican Peso', country: 'Mexico', countryCode: 'MX' },
    { code: 'INR', name: 'Indian Rupee', country: 'India', countryCode: 'IN' },
    { code: 'RUB', name: 'Russian Ruble', country: 'Russia', countryCode: 'RU' },
    { code: 'ZAR', name: 'South African Rand', country: 'South Africa', countryCode: 'ZA' },
    { code: 'TRY', name: 'Turkish Lira', country: 'Turkey', countryCode: 'TR' },
    { code: 'BRL', name: 'Brazilian Real', country: 'Brazil', countryCode: 'BR' },
    { code: 'TWD', name: 'New Taiwan Dollar', country: 'Taiwan', countryCode: 'TW' },
    { code: 'DKK', name: 'Danish Krone', country: 'Denmark', countryCode: 'DK' },
    { code: 'PLN', name: 'Polish Zloty', country: 'Poland', countryCode: 'PL' },
    { code: 'THB', name: 'Thai Baht', country: 'Thailand', countryCode: 'TH' },
    { code: 'IDR', name: 'Indonesian Rupiah', country: 'Indonesia', countryCode: 'ID' },
    { code: 'HUF', name: 'Hungarian Forint', country: 'Hungary', countryCode: 'HU' },
    { code: 'CZK', name: 'Czech Koruna', country: 'Czech Republic', countryCode: 'CZ' },
    { code: 'ILS', name: 'Israeli New Shekel', country: 'Israel', countryCode: 'IL' },
    { code: 'CLP', name: 'Chilean Peso', country: 'Chile', countryCode: 'CL' },
    { code: 'PHP', name: 'Philippine Peso', country: 'Philippines', countryCode: 'PH' },
    { code: 'AED', name: 'United Arab Emirates Dirham', country: 'United Arab Emirates', countryCode: 'AE' },
    { code: 'COP', name: 'Colombian Peso', country: 'Colombia', countryCode: 'CO' },
    { code: 'SAR', name: 'Saudi Riyal', country: 'Saudi Arabia', countryCode: 'SA' },
    { code: 'MYR', name: 'Malaysian Ringgit', country: 'Malaysia', countryCode: 'MY' },
    { code: 'RON', name: 'Romanian Leu', country: 'Romania', countryCode: 'RO' },
    { code: 'AFN', name: 'Afghan Afghani', country: 'Afghanistan', countryCode: 'AF' },
    { code: 'ALL', name: 'Albanian Lek', country: 'Albania', countryCode: 'AL' },
    { code: 'DZD', name: 'Algerian Dinar', country: 'Algeria', countryCode: 'DZ' },
    { code: 'AOA', name: 'Angolan Kwanza', country: 'Angola', countryCode: 'AO' },
    { code: 'XCD', name: 'East Caribbean Dollar', country: 'Antigua and Barbuda', countryCode: 'AG' },
    { code: 'ARS', name: 'Argentine Peso', country: 'Argentina', countryCode: 'AR' },
    { code: 'AMD', name: 'Armenian Dram', country: 'Armenia', countryCode: 'AM' },
    { code: 'AWG', name: 'Aruban Florin', country: 'Aruba', countryCode: 'AW' },
    { code: 'AZN', name: 'Azerbaijani Manat', country: 'Azerbaijan', countryCode: 'AZ' },
    { code: 'BSD', name: 'Bahamian Dollar', country: 'Bahamas', countryCode: 'BS' },
    { code: 'BHD', name: 'Bahraini Dinar', country: 'Bahrain', countryCode: 'BH' },
    { code: 'BDT', name: 'Bangladeshi Taka', country: 'Bangladesh', countryCode: 'BD' },
    { code: 'BBD', name: 'Barbadian Dollar', country: 'Barbados', countryCode: 'BB' },
    { code: 'BYN', name: 'Belarusian Ruble', country: 'Belarus', countryCode: 'BY' },
    { code: 'BZD', name: 'Belize Dollar', country: 'Belize', countryCode: 'BZ' },
    { code: 'XOF', name: 'West African CFA Franc', country: 'Benin', countryCode: 'BJ' },
    { code: 'BMD', name: 'Bermudian Dollar', country: 'Bermuda', countryCode: 'BM' },
    { code: 'BTN', name: 'Bhutanese Ngultrum', country: 'Bhutan', countryCode: 'BT' },
    { code: 'BOB', name: 'Bolivian Boliviano', country: 'Bolivia', countryCode: 'BO' },
    { code: 'BAM', name: 'Bosnia-Herzegovina Convertible Mark', country: 'Bosnia and Herzegovina', countryCode: 'BA' },
    { code: 'BWP', name: 'Botswana Pula', country: 'Botswana', countryCode: 'BW' },
    { code: 'BND', name: 'Brunei Dollar', country: 'Brunei', countryCode: 'BN' },
    { code: 'BGN', name: 'Bulgarian Lev', country: 'Bulgaria', countryCode: 'BG' },
    { code: 'BIF', name: 'Burundian Franc', country: 'Burundi', countryCode: 'BI' },
    { code: 'KHR', name: 'Cambodian Riel', country: 'Cambodia', countryCode: 'KH' },
    { code: 'XAF', name: 'Central African CFA Franc', country: 'Cameroon', countryCode: 'CM' },
    { code: 'CVE', name: 'Cape Verdean Escudo', country: 'Cape Verde', countryCode: 'CV' },
    { code: 'KYD', name: 'Cayman Islands Dollar', country: 'Cayman Islands', countryCode: 'KY' },
    { code: 'KMF', name: 'Comorian Franc', country: 'Comoros', countryCode: 'KM' },
    { code: 'CRC', name: 'Costa Rican Colón', country: 'Costa Rica', countryCode: 'CR' },
    { code: 'HRK', name: 'Croatian Kuna', country: 'Croatia', countryCode: 'HR' },
    { code: 'CUP', name: 'Cuban Peso', country: 'Cuba', countryCode: 'CU' },
    { code: 'DJF', name: 'Djiboutian Franc', country: 'Djibouti', countryCode: 'DJ' },
    { code: 'DOP', name: 'Dominican Peso', country: 'Dominican Republic', countryCode: 'DO' },
    { code: 'EGP', name: 'Egyptian Pound', country: 'Egypt', countryCode: 'EG' },
    { code: 'ETB', name: 'Ethiopian Birr', country: 'Ethiopia', countryCode: 'ET' },
    { code: 'FJD', name: 'Fijian Dollar', country: 'Fiji', countryCode: 'FJ' },
    { code: 'GMD', name: 'Gambian Dalasi', country: 'Gambia', countryCode: 'GM' },
    { code: 'GEL', name: 'Georgian Lari', country: 'Georgia', countryCode: 'GE' },
    { code: 'GHS', name: 'Ghanaian Cedi', country: 'Ghana', countryCode: 'GH' },
    { code: 'GTQ', name: 'Guatemalan Quetzal', country: 'Guatemala', countryCode: 'GT' },
    { code: 'GNF', name: 'Guinean Franc', country: 'Guinea', countryCode: 'GN' },
    { code: 'GYD', name: 'Guyanaese Dollar', country: 'Guyana', countryCode: 'GY' },
    { code: 'HTG', name: 'Haitian Gourde', country: 'Haiti', countryCode: 'HT' },
    { code: 'HNL', name: 'Honduran Lempira', country: 'Honduras', countryCode: 'HN' },
    { code: 'ISK', name: 'Icelandic Króna', country: 'Iceland', countryCode: 'IS' },
    { code: 'IQD', name: 'Iraqi Dinar', country: 'Iraq', countryCode: 'IQ' },
    { code: 'JMD', name: 'Jamaican Dollar', country: 'Jamaica', countryCode: 'JM' },
    { code: 'JOD', name: 'Jordanian Dinar', country: 'Jordan', countryCode: 'JO' },
    { code: 'KZT', name: 'Kazakhstani Tenge', country: 'Kazakhstan', countryCode: 'KZ' },
    { code: 'KES', name: 'Kenyan Shilling', country: 'Kenya', countryCode: 'KE' },
    { code: 'KWD', name: 'Kuwaiti Dinar', country: 'Kuwait', countryCode: 'KW' },
    { code: 'KGS', name: 'Kyrgystani Som', country: 'Kyrgyzstan', countryCode: 'KG' },
    { code: 'LAK', name: 'Laotian Kip', country: 'Laos', countryCode: 'LA' },
    { code: 'LBP', name: 'Lebanese Pound', country: 'Lebanon', countryCode: 'LB' },
    { code: 'LSL', name: 'Lesotho Loti', country: 'Lesotho', countryCode: 'LS' },
    { code: 'LRD', name: 'Liberian Dollar', country: 'Liberia', countryCode: 'LR' },
    { code: 'LYD', name: 'Libyan Dinar', country: 'Libya', countryCode: 'LY' },
    { code: 'MOP', name: 'Macanese Pataca', country: 'Macau', countryCode: 'MO' },
    { code: 'MKD', name: 'Macedonian Denar', country: 'Macedonia', countryCode: 'MK' },
    { code: 'MGA', name: 'Malagasy Ariary', country: 'Madagascar', countryCode: 'MG' },
    { code: 'MWK', name: 'Malawian Kwacha', country: 'Malawi', countryCode: 'MW' },
    { code: 'MVR', name: 'Maldivian Rufiyaa', country: 'Maldives', countryCode: 'MV' },
    { code: 'MRO', name: 'Mauritanian Ouguiya', country: 'Mauritania', countryCode: 'MR' },
    { code: 'MUR', name: 'Mauritian Rupee', country: 'Mauritius', countryCode: 'MU' },
    { code: 'MDL', name: 'Moldovan Leu', country: 'Moldova', countryCode: 'MD' },
    { code: 'MNT', name: 'Mongolian Tugrik', country: 'Mongolia', countryCode: 'MN' },
    { code: 'MAD', name: 'Moroccan Dirham', country: 'Morocco', countryCode: 'MA' },
    { code: 'MZN', name: 'Mozambican Metical', country: 'Mozambique', countryCode: 'MZ' },
    { code: 'MMK', name: 'Myanmar Kyat', country: 'Myanmar', countryCode: 'MM' },
    { code: 'NAD', name: 'Namibian Dollar', country: 'Namibia', countryCode: 'NA' },
    { code: 'NPR', name: 'Nepalese Rupee', country: 'Nepal', countryCode: 'NP' },
    { code: 'ANG', name: 'Netherlands Antillean Guilder', country: 'Netherlands Antilles', countryCode: 'AN' },
    { code: 'NIO', name: 'Nicaraguan Córdoba', country: 'Nicaragua', countryCode: 'NI' },
    { code: 'NGN', name: 'Nigerian Naira', country: 'Nigeria', countryCode: 'NG' },
    { code: 'OMR', name: 'Omani Rial', country: 'Oman', countryCode: 'OM' },
    { code: 'PKR', name: 'Pakistani Rupee', country: 'Pakistan', countryCode: 'PK' },
    { code: 'PAB', name: 'Panamanian Balboa', country: 'Panama', countryCode: 'PA' },
    { code: 'PGK', name: 'Papua New Guinean Kina', country: 'Papua New Guinea', countryCode: 'PG' },
    { code: 'PYG', name: 'Paraguayan Guarani', country: 'Paraguay', countryCode: 'PY' },
    { code: 'PEN', name: 'Peruvian Nuevo Sol', country: 'Peru', countryCode: 'PE' },
    { code: 'QAR', name: 'Qatari Rial', country: 'Qatar', countryCode: 'QA' },
    { code: 'RWF', name: 'Rwandan Franc', country: 'Rwanda', countryCode: 'RW' },
    { code: 'WST', name: 'Samoan Tala', country: 'Samoa', countryCode: 'WS' },
    { code: 'STD', name: 'São Tomé and Príncipe Dobra', country: 'São Tomé and Príncipe', countryCode: 'ST' },
    { code: 'RSD', name: 'Serbian Dinar', country: 'Serbia', countryCode: 'RS' },
    { code: 'SCR', name: 'Seychellois Rupee', country: 'Seychelles', countryCode: 'SC' },
    { code: 'SLL', name: 'Sierra Leonean Leone', country: 'Sierra Leone', countryCode: 'SL' },
    { code: 'SBD', name: 'Solomon Islands Dollar', country: 'Solomon Islands', countryCode: 'SB' },
    { code: 'SOS', name: 'Somali Shilling', country: 'Somalia', countryCode: 'SO' },
    { code: 'LKR', name: 'Sri Lankan Rupee', country: 'Sri Lanka', countryCode: 'LK' },
    { code: 'SDG', name: 'Sudanese Pound', country: 'Sudan', countryCode: 'SD' },
    { code: 'SRD', name: 'Surinamese Dollar', country: 'Suriname', countryCode: 'SR' },
    { code: 'SZL', name: 'Swazi Lilangeni', country: 'Swaziland', countryCode: 'SZ' },
    { code: 'SYP', name: 'Syrian Pound', country: 'Syria', countryCode: 'SY' },
    { code: 'TJS', name: 'Tajikistani Somoni', country: 'Tajikistan', countryCode: 'TJ' },
    { code: 'TZS', name: 'Tanzanian Shilling', country: 'Tanzania', countryCode: 'TZ' },
    { code: 'TOP', name: 'Tongan Paʻanga', country: 'Tonga', countryCode: 'TO' },
    { code: 'TTD', name: 'Trinidad and Tobago Dollar', country: 'Trinidad and Tobago', countryCode: 'TT' },
    { code: 'TND', name: 'Tunisian Dinar', country: 'Tunisia', countryCode: 'TN' },
    { code: 'TMT', name: 'Turkmenistani Manat', country: 'Turkmenistan', countryCode: 'TM' },
    { code: 'UGX', name: 'Ugandan Shilling', country: 'Uganda', countryCode: 'UG' },
    { code: 'UAH', name: 'Ukrainian Hryvnia', country: 'Ukraine', countryCode: 'UA' },
    { code: 'UYU', name: 'Uruguayan Peso', country: 'Uruguay', countryCode: 'UY' },
    { code: 'UZS', name: 'Uzbekistan Som', country: 'Uzbekistan', countryCode: 'UZ' },
    { code: 'VUV', name: 'Vanuatu Vatu', country: 'Vanuatu', countryCode: 'VU' },
    { code: 'VEF', name: 'Venezuelan Bolívar', country: 'Venezuela', countryCode: 'VE' },
    { code: 'VND', name: 'Vietnamese Dong', country: 'Vietnam', countryCode: 'VN' },
    { code: 'YER', name: 'Yemeni Rial', country: 'Yemen', countryCode: 'YE' },
    { code: 'ZMW', name: 'Zambian Kwacha', country: 'Zambia', countryCode: 'ZM' },
    { code: 'ZWL', name: 'Zimbabwean Dollar', country: 'Zimbabwe', countryCode: 'ZW' },
];
